In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from matplotlib import rc

rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

In [3]:
demo_df = pd.read_csv("LPOINT_BIG_COMP_01_DEMO.csv")
pdde_df = pd.read_csv("LPOINT_BIG_COMP_02_PDDE.csv")
cop_df = pd.read_csv("LPOINT_BIG_COMP_03_COP_U.csv")
pd_df = pd.read_csv("LPOINT_BIG_COMP_04_PD_CLAC.csv")
br_df = pd.read_csv("LPOINT_BIG_COMP_05_BR.csv")
lpay_df = pd.read_csv("LPOINT_BIG_COMP_06_LPAY.csv")

/var/folders/z_/ns3pdgbs27x7bmf6wgkkg19r0000gn/T/ipykernel_2505/4235936177.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  pdde_df = pd.read_csv("LPOINT_BIG_COMP_02_PDDE.csv")

In [4]:
cus_join = pd.merge(demo_df,pdde_df, on="cust", how='inner')
cus_join

,cust,ma_fem_dv,ages,zon_hlv,rct_no,chnl_dv,cop_c,br_c,pd_c,de_dt,de_hr,buy_am,buy_ct
0,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,20210116,18,59000.0,1
1,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,20210116,18,19000.0,1
2,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0796,20210116,18,100.0,1
3,M000034966,여성,40대,Z07,A01016718167,1,A01,A010045,PD0816,20210116,18,62100.0,1
4,M000034966,여성,40대,Z07,A02357398521,1,A02,A020116,PD0630,20210325,13,19900.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4381738,M999962961,여성,50대,Z17,A05001012161,1,A05,A050039,PD0541,20210313,20,599000.0,1
4381739,M999962961,여성,50대,Z17,E06002810292,2,A06,NaN,PD0959,20210113,18,129000.0,1
4381740,M999962961,여성,50대,Z17,E06004609359,2,A06,NaN,PD0954,20210122,14,34300.0,1
4381741,M999962961,여성,50대,Z17,E06025413888,2,A06,NaN,PD0967,20210406,17,89000.0,1
4381742,M999962961,여성,50대,Z17,E06035713248,2,A06,NaN,PD1889,20210503,22,50000.0,1

In [5]:
cus_merge = pd.merge(cus_join,pd_df, on ='pd_c', how='inner' )
cus_merge

,cust,ma_fem_dv,ages,zon_hlv,rct_no,chnl_dv,cop_c,br_c,pd_c,de_dt,de_hr,buy_am,buy_ct,pd_nm,clac_hlv_nm,clac_mcls_nm
0,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,20210116,18,59000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
1,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,20210116,18,19000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
2,M000136117,여성,30대,Z11,A01294575336,1,A01,A010018,PD0777,20210805,15,239000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
3,M000261625,여성,40대,Z17,A01117216600,1,A01,A010017,PD0777,20210403,13,179000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
4,M000419293,여성,40대,Z17,A02041463489,1,A02,A020008,PD0777,20210129,14,3000.0,3,남성런닝/트레이닝화,스포츠패션,남성스포츠화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4381738,M858719851,여성,60대,Z16,A05001516873,1,A05,A050072,PD0995,20210430,10,139000.0,1,보이스레코더,영상/음향가전,소형디지털가전
4381739,M880029153,남성,40대,Z16,E06043468594,2,A06,NaN,PD0917,20210712,21,199000.0,1,미니벨로,아웃도어/레저,자전거
4381740,M986268092,남성,40대,Z09,E06040602652,2,A06,NaN,PD0917,20210523,8,187050.0,1,미니벨로,아웃도어/레저,자전거
4381741,M926014276,남성,40대,Z10,A02105319111,1,A02,A020023,PD1059,20210828,17,800000.0,8,분양,원예/애완,동물병원
4381742,M962869931,여성,20대,Z16,E06011348557,2,A06,NaN,PD0442,20210220,14,49500.0,1,절단기,문구/사무용품,사무기기

In [9]:
cus_merge.loc[((cus_merge['cop_c'] == 'A01') | (cus_merge['cop_c'] == 'A06')),:]['clac_hlv_nm'].unique()

array(['스포츠패션', '속옷/양말/홈웨어', '건해산물', '여성의류', '냉동식품', '채소', '음료',
       '청소/세탁/욕실용품', '주류', '과자', '조미료', '과일', '대용식', '원예/애완', '완구',
       '패션잡화', '퍼스널케어', '침구/수예', '식기/조리기구', '양곡', '모바일', '아웃도어/레저',
       '화장품/뷰티케어', '남성의류', '병통조림', '헬스/피트니스', '문구/사무용품', '조리식품',
       '생활/주방가전', '유아동의류', '세제/위생', '주방잡화', '생활/렌탈서비스', '수산물', '축산물',
       '유아식품', '건강식품', '구기/필드스포츠', '가구', '시즌스포츠', '건강용품', '냉장/세탁가전',
       '커피/차', '계절가전', '공구/안전용품', '영상/음향가전', '기타(비상품)', '출산/육아용품', '컴퓨터',
       '여행/레저서비스', '상품권', '자동차용품', '서적/음반/악기', '담배', '인테리어/조명'],
      dtype=object)

In [6]:
# 선물하기에 적합하지 않아 대분류중에서 아예 뺄 것들
index1 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '냉장식품') | (cus_merge['clac_hlv_nm'] == '유제품') | (cus_merge['clac_hlv_nm'] == '테넌트/음식점'), : ].index
cus_merge.drop(index1, axis=0, inplace = True)

In [7]:
# 선물하기에 적합하지 않은 대분류중에서 상품명이 선물하기에 적합한 것들 제외하고 빼기
index2 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '건해산물') & ((cus_merge['pd_nm'] != '김선물세트') | (cus_merge['pd_nm'] != '멸치선물세트') | (cus_merge['pd_nm'] != '굴비선물세트') | (cus_merge['pd_nm'] != '기타건해산물선물세트')) , : ].index
index3 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '채소') & ((cus_merge['pd_nm'] != '혼합채소선물세트') | (cus_merge['pd_nm'] != '버섯선물세트') | (cus_merge['pd_nm'] != '기타한방약재') | (cus_merge['pd_nm'] != '수삼선물세트') | (cus_merge['pd_nm'] != '약용버섯류') | (cus_merge['pd_nm'] != '인삼류')) , : ].index
index4 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '조미료') & ((cus_merge['pd_nm'] != '조미료세트') | (cus_merge['pd_nm'] != '조미혼합세트') | (cus_merge['pd_nm'] != '식용유세트')) , : ].index
index5 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '양곡') & (cus_merge['pd_nm'] != '곡물선물세트') , : ].index
index6 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '병통조림') & ((cus_merge['pd_nm'] != '통조림혼합세트') | (cus_merge['pd_nm'] != '참치통조림세트') ) , : ].index
index7 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '조리식품') & ((cus_merge['pd_nm'] != '케이크') | (cus_merge['pd_nm'] != '롤') | (cus_merge['pd_nm'] != '선물류') | (cus_merge['pd_nm'] != '일반떡') | (cus_merge['pd_nm'] != '치킨류') | (cus_merge['pd_nm'] != '도넛')| (cus_merge['pd_nm'] != '피자')) , : ].index
index8 = cus_merge.loc[(cus_merge['clac_hlv_nm'] == '수산물') & ((cus_merge['pd_nm'] != '생선선물세트') | (cus_merge['pd_nm'] != '해물선물세트') | (cus_merge['pd_nm'] != '혼합수산선물세트') ) , : ].index

In [8]:
cus_merge.drop(index2, axis=0, inplace=True)
cus_merge.drop(index3, axis=0, inplace=True)
cus_merge.drop(index4, axis=0, inplace=True)
cus_merge.drop(index5, axis=0, inplace=True)
cus_merge.drop(index6, axis=0, inplace=True)
cus_merge.drop(index7, axis=0, inplace=True)
cus_merge.drop(index8, axis=0, inplace=True)

In [9]:
# 타켓으로 생각한 304050대 분들
cus_304050 = cus_merge.loc[((cus_merge['ages'] == '30대') | (cus_merge['ages'] == '40대')| (cus_merge['ages'] == '50대')) & ((cus_merge['cop_c'] == 'A01') |  (cus_merge['cop_c'] == 'A06')) , : ]
cus_304050

,cust,ma_fem_dv,ages,zon_hlv,rct_no,chnl_dv,cop_c,br_c,pd_c,de_dt,de_hr,buy_am,buy_ct,pd_nm,clac_hlv_nm,clac_mcls_nm
0,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,20210116,18,59000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
1,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,20210116,18,19000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
2,M000136117,여성,30대,Z11,A01294575336,1,A01,A010018,PD0777,20210805,15,239000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
3,M000261625,여성,40대,Z17,A01117216600,1,A01,A010017,PD0777,20210403,13,179000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
6,M000508243,여성,50대,Z17,A01417352264,1,A01,A010032,PD0777,20211031,18,49000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4381733,M762888764,여성,30대,Z11,E06033428238,2,A06,NaN,PD1010,20210428,10,28580.0,1,기타광학기기,영상/음향가전,카메라/캠코더
4381735,M897387507,남성,40대,Z07,E06015295559,2,A06,NaN,PD0912,20210307,10,908000.0,1,전동보드/전동킥보드,아웃도어/레저,인라인/스케이트보드/킥보드
4381736,M802756595,남성,40대,Z17,E06006556124,2,A06,NaN,PD0066,20210131,19,229000.0,1,녹즙기/원액기,건강용품,건강가전
4381739,M880029153,남성,40대,Z16,E06043468594,2,A06,NaN,PD0917,20210712,21,199000.0,1,미니벨로,아웃도어/레저,자전거
4381740,M986268092,남성,40대,Z09,E06040602652,2,A06,NaN,PD0917,20210523,8,187050.0,1,미니벨로,아웃도어/레저,자전거

In [10]:
from datetime import datetime, date
cus_304050['de_dt'] = pd.to_datetime(cus_304050['de_dt'],format='%Y%m%d')

<ipython-input-10-229d9df4bf9a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cus_304050['de_dt'] = pd.to_datetime(cus_304050['de_dt'],format='%Y%m%d')

## 직장동료

In [13]:
# 주말과 공휴일 제외하고 12시 이전과 오후 1시부터 6시 사이를 근무시간이라 생각해 그 때 오프라인 구매하신 분들을 제외
q = cus_304050[cus_304050['chnl_dv'] == 1]
qq = q[((q['de_hr'] >= 12) & (q['de_hr'] <= 13)) | (q['de_hr'] >= 18)]
qqq = qq[(qq['de_dt'].dt.dayofweek != 5) | (qq['de_dt'].dt.dayofweek != 6)]
qqqq = qqq[(qqq['de_dt'] == '2021-01-01')|(qqq['de_dt'] == '2021-02-11')|(qqq['de_dt'] == '2021-02-12') \
                   |(qqq['de_dt'] == '2021-03-01')|(qqq['de_dt'] == '2021-05-05')|(qqq['de_dt'] == '2021-05-19')|(qqq['de_dt'] == '2021-09-20')|(qqq['de_dt'] == '2021-09-21')|(qqq['de_dt'] == '2021-09-22')]
qqqq

,cust,ma_fem_dv,ages,zon_hlv,rct_no,chnl_dv,cop_c,br_c,pd_c,de_dt,de_hr,buy_am,buy_ct,pd_nm,clac_hlv_nm,clac_mcls_nm
82,M007463920,남성,40대,Z08,A01355815946,1,A01,A010038,PD0777,2021-09-20,12,55000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
83,M007463920,남성,40대,Z08,A01355818225,1,A01,A010038,PD0777,2021-09-20,12,26000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
305,M019728616,여성,30대,Z10,A01358580336,1,A01,A010028,PD0777,2021-09-22,18,109000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
306,M019728616,여성,30대,Z10,A01358580336,1,A01,A010028,PD0777,2021-09-22,18,109000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
531,M034251158,남성,40대,Z17,A01166362522,1,A01,A010003,PD0777,2021-05-05,18,129000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4378860,M278581509,남성,50대,Z11,A01188012940,1,A01,A010049,PD0652,2021-05-19,19,34300.0,1,유아동속옷세트,속옷/양말/홈웨어,유아동속옷
4378871,M541663654,여성,30대,Z11,A01072022260,1,A01,A010049,PD0652,2021-03-01,12,9900.0,1,유아동속옷세트,속옷/양말/홈웨어,유아동속옷
4379453,M368621241,여성,50대,Z17,A01187979604,1,A01,A010017,PD0907,2021-05-19,19,261000.0,1,등산지팡이/스틱,아웃도어/레저,등산
4380623,M664658841,여성,30대,Z17,A01356764543,1,A01,A010001,PD0088,2021-09-22,12,5500.0,1,안전상비의약품세트,건강용품,일반의약품
4381316,M207638686,여성,30대,Z06,A01000278214,1,A01,A010053,PD0516,2021-01-01,18,142400.0,1,제화/패션/주유상품권,상품권,지류상품권

In [46]:
worker = qqq.drop(qqqq.index)
worker

,cust,ma_fem_dv,ages,zon_hlv,rct_no,chnl_dv,cop_c,br_c,pd_c,de_dt,de_hr,buy_am,buy_ct,pd_nm,clac_hlv_nm,clac_mcls_nm
0,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,2021-01-16,18,59000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
1,M000034966,여성,40대,Z07,A01016688590,1,A01,A010045,PD0777,2021-01-16,18,19000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
3,M000261625,여성,40대,Z17,A01117216600,1,A01,A010017,PD0777,2021-04-03,13,179000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
6,M000508243,여성,50대,Z17,A01417352264,1,A01,A010032,PD0777,2021-10-31,18,49000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
11,M001694463,남성,40대,Z14,A01139531032,1,A01,A010030,PD0777,2021-04-17,19,250000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4381721,M740326708,여성,40대,Z17,A01171190884,1,A01,A010002,PD0583,2021-05-08,18,300000.0,1,국악악기,서적/음반/악기,악기
4381722,M740326708,여성,40대,Z17,A01171192292,1,A01,A010002,PD0583,2021-05-08,18,300000.0,1,국악악기,서적/음반/악기,악기
4381723,M740326708,여성,40대,Z17,A01171195251,1,A01,A010002,PD0583,2021-05-08,18,350000.0,1,국악악기,서적/음반/악기,악기
4381724,M740326708,여성,40대,Z17,A01171199385,1,A01,A010002,PD0583,2021-05-08,18,40000.0,1,국악악기,서적/음반/악기,악기
4381730,M949264778,여성,50대,Z12,A01298342312,1,A01,A010012,PD0533,2021-08-08,12,93000.0,1,에어워셔,생활/주방가전,공기청정/가습/제습

In [51]:
# 필터링한 분들 중에서 정장류를 구매하신분들이라면 직장인일 확률이 높을 것이다
display(worker.loc[(worker['pd_nm'] == '남성정장셔츠') | (worker['pd_nm'] == '남성정장화') | (worker['pd_nm'] == '여성정장세트')| (worker['pd_nm'] == '남성정장세트')| (worker['pd_nm'] == '남성정장재킷')| (worker['pd_nm'] == '남성정장바지'),:])
cust_woker = worker.loc[(worker['pd_nm'] == '남성정장셔츠') | (worker['pd_nm'] == '남성정장화') | (worker['pd_nm'] == '여성정장세트')| (worker['pd_nm'] == '남성정장세트')| (worker['pd_nm'] == '남성정장재킷')| (worker['pd_nm'] == '남성정장바지'),:]['cust'].unique()

,cust,ma_fem_dv,ages,zon_hlv,rct_no,chnl_dv,cop_c,br_c,pd_c,de_dt,de_hr,buy_am,buy_ct,pd_nm,clac_hlv_nm,clac_mcls_nm
1942020,M000494848,여성,30대,Z10,A01440839579,1,A01,A010028,PD0291,2021-11-17,12,89000.0,1,남성정장셔츠,남성의류,남성의류상의
1942032,M007207067,남성,50대,Z12,A01415625133,1,A01,A010030,PD0291,2021-10-31,12,29000.0,1,남성정장셔츠,남성의류,남성의류상의
1942036,M007319872,여성,50대,Z12,A01078185864,1,A01,A010037,PD0291,2021-03-06,12,120000.0,1,남성정장셔츠,남성의류,남성의류상의
1942060,M016404339,남성,30대,Z10,A01203713331,1,A01,A010007,PD0291,2021-05-30,18,99000.0,1,남성정장셔츠,남성의류,남성의류상의
1942061,M016404339,남성,30대,Z10,A01203713331,1,A01,A010007,PD0291,2021-05-30,18,99000.0,1,남성정장셔츠,남성의류,남성의류상의
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4086604,M920565826,남성,40대,Z17,A01393913412,1,A01,A010008,PD0308,2021-10-16,19,620000.0,1,남성정장바지,남성의류,남성의류하의
4086605,M923285900,여성,30대,Z17,A01396321610,1,A01,A010003,PD0308,2021-10-17,18,882000.0,1,남성정장바지,남성의류,남성의류하의
4086606,M938201564,여성,40대,Z11,A01253572117,1,A01,A010045,PD0308,2021-07-04,13,19900.0,1,남성정장바지,남성의류,남성의류하의
4086608,M965981972,여성,30대,Z04,A01394422904,1,A01,A010027,PD0308,2021-10-17,12,225000.0,1,남성정장바지,남성의류,남성의류하의
4086609,M971914997,여성,30대,Z04,A01319395738,1,A01,A010045,PD0308,2021-08-26,13,9900.0,1,남성정장바지,남성의류,남성의류하의

In [54]:
worker_suit = cus_304050[cus_304050['cust'].isin(cust_woker)]
worker_suit

,cust,ma_fem_dv,ages,zon_hlv,rct_no,chnl_dv,cop_c,br_c,pd_c,de_dt,de_hr,buy_am,buy_ct,pd_nm,clac_hlv_nm,clac_mcls_nm
11,M001694463,남성,40대,Z14,A01139531032,1,A01,A010030,PD0777,20210417,19,250000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
12,M001694463,남성,40대,Z14,A01269386623,1,A01,A010030,PD0777,20210716,19,65000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
13,M001694463,남성,40대,Z14,A01299890479,1,A01,A010030,PD0777,20210808,19,29000.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
33,M003803545,여성,40대,Z16,A01148988767,1,A01,A010045,PD0777,20210425,11,26700.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
34,M003803545,여성,40대,Z16,A01149256806,1,A01,A010045,PD0777,20210425,13,26700.0,1,남성런닝/트레이닝화,스포츠패션,남성스포츠화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4381644,M485343693,여성,30대,Z12,A01398007523,1,A01,A010012,PD0542,20211019,17,619000.0,1,헤어롤,생활/주방가전,이미용가전
4381645,M485343693,여성,30대,Z12,A01401256109,1,A01,A010012,PD0542,20211022,14,619000.0,1,헤어롤,생활/주방가전,이미용가전
4381675,M766516104,남성,30대,Z10,E06002050706,2,A06,NaN,PD0443,20210110,10,41800.0,1,파쇄기,문구/사무용품,사무기기
4381679,M707775545,남성,30대,Z11,A01052238361,1,A01,A010004,PD0972,20210215,16,49000.0,1,여성한복,여성의류,여성특수목적의류
4381682,M478984379,여성,40대,Z17,E06008433212,2,A06,NaN,PD0421,20210206,12,14080.0,1,광학기기/과학상자,문구/사무용품,교육보조재

In [55]:
worker_suit.to_csv("직장인.csv")